import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";
import Section from "../components/Section";
import { BsCheckLg, BsLink } from "react-icons/bs";
import Footer from "../components/Footer";

const Home: NextPage = () => {
  const submitHandler = (e: any) => {
    e.preventDefault();

    const data: FormData = new FormData(e.target);
    const payload = Object.fromEntries(data.entries());
    const headers = new Headers();
    headers.append("Content-Type", "application/json");

    const request = {
      url: payload.url,
      short: "",
      expiry: 24,
    };

    console.log(request);

    fetch("http://localhost:4001/v1/shorten", {
      method: "POST",
      body: JSON.stringify(request),
      headers: headers,
    })
      .then((response) =>
        response.json().then((data) => {
          console.log(data);
        })
      )
      .catch((err) => console.log(err));

    console.log("form was submitted");
  };
  return (
    <div className="min-h-screen flex flex-col  bg-gradient-to-r from-sky-400 to-blue-500">
      <Head>
        <title>URL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Section className="justify-center lg:flex-row flex-col mt-20 gap-16">
        <div className="flex justify-center items-center p-4 bg-[#F8F9FA] rounded-xl">
          <div className="p-5 py-8">
            <form onSubmit={submitHandler} className="flex flex-col gap-6">
              {/* URL */}
              <div className="flex flex-col gap-3">
                <label className="text-xl  font-bold">
                  Enter URL to Shorten
                </label>

                <div className="flex items-center w-[375px] rounded-lg bg-white border-[1px] border-gray-900 p-4 gap-2">
                  <label htmlFor="url" className="">
                    <BsLink className="text-2xl font-medium text-black" />
                  </label>

                  <input
                    className="flex-1 outline-none rounded-r-lg  text-black"
                    type="text"
                    name="url"
                    id="url"
                    autoFocus={true}
                  />
                </div>
              </div>

              {/* ALIAS */}
              <div className="flex flex-col gap-3">
                <label className="text-xl font-bold">Customize your link</label>

                <div className="flex flex-col w-[375px] rounded-lg bg-white border-[1px] border-gray-900 gap-2">
                  <div className="grid grid-cols-3 items-center gap-2">
                    <div className="col-span-2 border-r-[1px] border-gray-700 p-4 text-center">
                      <label className="text-lg font-medium tracking-wide">
                        shortenURL.com
                      </label>
                    </div>

                    <div className="items-center">
                      <input
                        className="outline-none px-2 w-full rounded-r-lg  text-black placeholder:font-extralight"
                        placeholder="alias"
                        type="text"
                        name="url"
                      />
                    </div>
                  </div>
                </div>
              </div>

              <button
                type="submit"
                className="px-5 py-4 rounded-md bg-blue-600 text-white font-semibold transition-all hover:bg-blue-700"
              >
                Shorten URL
              </button>
            </form>
          </div>
        </div>

        {/* GET STARTED */}

        <div className="flex flex-col gap-4 justify-center text-white">
          <h1 className="text-lg font-poppinsl">
            Welcome to <br />{" "}
            <span className="text-4xl font-bungee">shortURL</span>{" "}
          </h1>

          <p className="text-md font-medium">
            Get Started For Free! Dont miss out on:{" "}
          </p>

          <div className="flex flex-col gap-2">
            <div className="flex items-center gap-2">
              <BsCheckLg className="text-green-500" />
              <p className="text-lg">Customizable URLs</p>
            </div>
            <div className="flex items-center gap-2">
              <BsCheckLg className="text-green-500" />
              <p className="text-lg">Managing Link History</p>
            </div>
            <div className="flex items-center gap-2">
              <BsCheckLg className="text-green-500" />
              <p className="text-lg">Link Analysis</p>
            </div>
          </div>

          <a
            href="/signup"
            className="text-md font-medium text-white bg-blue-600 px-8 py-3 w-fit rounded-lg select-none transition-all hover:bg-blue-800 hover:underline"
          >
            Get Started
          </a>
        </div>
      </Section>
      <Footer />
    </div>
  );
};

export default Home;
