version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pa55word
      - POSTGRES_DB=shorturl
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - SHORTURL_DB_DSN=postgres://root:pa55word@postgres:5432/shorturl?sslmode=disable
      - REDIS_ADDR=redis:6379
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
